spring:
  application:
    name: app
  profiles:
    default: development
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: ${PORT:8080}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
